[buildPlans.adamantium]
family = "Adamantium"
spacing = "normal"
serifs = "slab"
no-cv-ss = true
export-glyph-names = false

  [buildPlans.adamantium.variants]
  inherits = "ss04"

[buildPlans.adamantium.weights.light]
shape = 300
menu = 300
css = 300

[buildPlans.adamantium.weights.regular]
shape = 400
menu = 400
css = 400

[buildPlans.adamantium.weights.heavy]
shape = 900
menu = 900
css = 900
